[program:app_asturiasMobile]
command=/home/erpnext/.services/app_asturiasMobile/venv/bin/gunicorn app.main:app -c deploy/scripts/gunicorn_conf.py
directory=/home/erpnext/.services/app_asturiasMobile
user=erpnext
autostart=true
autorestart=true
startretries=3
startsecs=10
stopwaitsecs=30
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/app_asturiasMobile/app.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=
    APP_ENV="production",
    LOG_FORMAT="json"
